- app/Http/Controllers/ImageController.php
- storage/app/images/flags/default-flag.svg
and upon failure default to a standard image.
There are various ways to implement this, including separately defining `$extensions` in each function for image types unique to flags or books and passing that as a function parameter to `getImage(...)`.
> ImageController.php: Extend ImageController to try various file extensions

- .github/workflows/build-and-push.yml
- docker-compose-jellyfin.yml
- docker-compose.yml
- docker/PhpDockerfile
Instructions in the workflow file
With this, when you push to main, it will kickstart making the Docker images for PHP and Python images, which appear under repo -> Code -> Packages
This effectively resolves Issue #48 
Extend it by updating `docker-compose*.yml` to use e.g. `image: ghcr.io/simjanos-dev/linguacafe-webserver:main` and  `image: ghcr.io/simjanos-dev/linguacafe-python-service:main`. Then nobody needs to build an image
Can be improved by upgrading node: its install script sleeps for 20 seconds and 60 seconds warning about old node.
> ghcr.io Docker image workflow

- .dockerignore
- docker-compose.yml
- docker/PhpDockerfile
- docker/PythonDockerfile
This is for the most part, a refactor of the dockerfiles to follow most* of the best practices:
- Successive `RUN` commands have been consolidated into groups according to what they do.
- Quotes were added where words could be split.
- Setup is done to ensure build fails if command before pipe fails to prevent a potentially "corrupted" image.
- `pip`now installs packages without cache.
- `apt-get` is used instead of `apt` and its cache is cleared at the end.
Those two last points allowed images to down from 1.70 GB and 1.42 GB to 1.26 GB and 1.17 GB on my fork, a little more than a 20% reduction.
This PR also removes the `.dockerignore` file added earlier since now that persistent files never touch the repo it serves no purpose. A lot of those `.gitignore` files scattered around could be …
> Dockerfile refactor

- docker/PhpDockerfile
This commit moves the compiling of the JavaScript code into a separate container, from which it is copied over to the final image to ensure no JavaScript dependencies are bloating the end result. On first testing this reduced image size by around 400MB.
I will do more testing for some days since it is hard to believe this 35~ish percent reduction didn't break anything.
I also noticed I had permission issues with the Laravel log despite me running `chmod -R ./ 777` on the folder after pulling but before starting the container; I will look into whatever is going on there.
> feat: reduce image size using a multi stage build

- .github/workflows/build-and-push.yml
This small change will make it so that images build and published to ghcr.io will be tagged with the name of their respective release tag, and the most recent one will have the 'latest' tag on top of it.
I'm not sure but I think when you first merge this to main it will trigger the old action and build an image with the "main" tag, and from there onward it will only build when doing a release. So if you do both things in quick succession the last of all "main" images will be the same as "v0.7".
> feat: change the action from build on commit to main to build on release

- docker-compose.yml
- storage/models/.gitignore
This commit changes the default tag pulled by the images from 'main' to 'latest', which will be automatically given to the most recent image built from the latest release, while also enabling it to be changed to a specific version by specifying it in a .env file.
It also creates the new models directory to store the Spacy files for the extra languages, and modifies the PYTHONPATH environment variable to append this folder to it.
This will remain a draft until we figure out every little detail about locally installing models, specially since people pulling this before the 0.7 release will have it break on them (can be solved by changing the version in the .env file).
> feat: add compatibility with versioned images and local models

- docker-compose.yml
This commit makes it so that users of Apple Silicon no longer need to comment out a line to run the python container nor remember to comment it back in when updating; the process is now handled by an enviroment variable like all the other deployment settings.
It also silences a warning when trying to append a directory to the PYTHONPATH environment variable inside the container because the variable is not set up by default. Now it is simply overwritten.
> fix: commenting in and out is no longer needed and silenced warning

- docker/PythonDockerfile
- tools/tokenizer.py
This PR consist of two separate commits so that they could be split into separate PRs in case there is trouble with one of them.
The first commit adds support to locally install the Spacy models for Thai and Turkish, of which I picked the smallest models available that had been maintained on the last year. Tagalog was excluded because the wheel provided has issues when trying to install it so it will be addressed later on. The only Vietnamese model I found [does not work with current versions of Spacy](https://github.com/trungtv/vi_spacy/issues/10) so even if I got it installed it wouldn't load.
The second commit adds the Python side of actually loading and using the models. I tested it by sending the raw text and the language as JSON to the `/tokenizer` route and I successfully got a …
> Thai and Turkish support for the Python side

- resources/js/components/Text/TextBlockGroup.vue
Previously, first two words in phrase were joined and there was a space after the phrase: `Säpsähdän hereille` became `Säpsähdänhereille ` which resulted in mispronunciation. This change fixes the resulting `text` to the correct one.
> Fix spacing in TTS for phrases

- docker-compose-dev-macos.yml
- docker-compose-dev.yml
- docker-compose.yml
By default the depends_on condition only guarantees that the "mysql" container will be built before the "webserver" container. This PR adds an health check and condition to the "mysql" container that makes sure that the "webserver" will be started only after the mysql database is ready to allow incoming connections.
> Feature: Add condition to depends_on and healthcheck for mysql

- docker-compose-dev-macos.yml
- docker-compose-dev.yml
- docker-compose.yml
- docker/PythonDockerfile
- docker/PythonDockerfileDev
- tools/tokenizer.py
The first commit performs a series of very small refactors that I think make sense, such as moving the non configurable settings from the composefile to the image itself, and using a python base image instead of an ubuntu one just to install python on it immediately.
The second commit "fixes" a bug I encountered when testing the import book functionality where `sortedItems` would not be defined, most likely because `sortMethod` was neither of the options checked, which raised an exception when trying to access it later.
I made it so that it gets the default behaviour whenever the "spine" option is **not** selected, and isolated it on its own commit so it can be easily left out if you'd rather address the issue by different means.
> Streamline the build and use of the Python image

- docker-compose-dev-macos.yml
- docker-compose-dev.yml
- docker/PythonDockerfileDev
This commit reverts the process of setting the PYTHONPATH on the dev environment to being done on the composefile instead of doing it during the build process.
> fix: revert to setting PYTHONPATH on the composefile for dev

- docker-compose-dev-macos.yml
- docker-compose-dev.yml
- docker-compose.yml
- docker/PythonDockerfile
- docker/PythonDockerfileDev
This commit reverts #294 and most of #284 except for the small fix when importing ebooks. There is also a small commit that adds back the change of the base image since that was worth keeping and didn't break anything (I expect).
> Revert #294 and #284

- .github/workflows/beta-image.yml
This action can be manually launched from any branch but it really should only ever be used from the `beta` one.
It tags the image with `${branch_name}` and with `${branch_name}-YYYY-MM-DD` so that it is possible to both get the latest beta image with a simple pull and to pin a version with accuracy of a day; if an image is rebuilt within the same day it will be overwritten.
This needs to be merged into `main` for it to be visible in the *Actions* tab, but i'm not really sure if it has to be copied over to the `beta` branch too.
> feat: added new action to build a beta image

- resources/js/components/Vocabulary/VocabularyExportDialog.vue
Closes #237 
Also found small issue, if the user selects "selectAll" option and then unselect any of the other options, the "selectAll" option is still selected even if it's not longer valid.
I added code that unselects the "selectAll" in such case.
> Feature/change voc export UI to checkboxes

- install_linguacafe.bat
Update install script to close #258 
Remove git requirement, add storage folder at first install.
Use curl, which is installed since Windows 10, if we want to support install on Windows 7/8 I could rewrite the script to use a call to powershell instead, but i don't have machines to test it...
> remove git requirement, use curl for download docker compose

- database/seeders/FontTypeSeeder.php
The default font "NotoSans JP" does not render some diacritics very well, in particular, the háček used in several Slavic languages and the acute accent in Greek. The effected languages: Croatian, Czech, Greek, Macedonian, and Slovenian have all been transferred to the "OpenSans" default font group which renders the mentioned diacritics properly.
| NotoSans JP | OpenSans |
| ----------- | -------- |
|![croatian_noto_jp](https://github.com/user-attachments/assets/eec321a0-60ca-4842-ad40-b74d552573ba)|![croatian_open_sans](https://github.com/user-attachments/assets/7895ab09-5981-49c7-ac42-c650134abcd1)
|![czech_noto_jp](https://github.com/user-attachments/assets/63d5cbd4-f4cd-4038-8c71-544d1df36e91)|![czech_open_sans](https://github.com/user-attachments/assets/a6400b97-7b82-4d0a-b929-2d61979 …
> fix: language default fonts

- resources/sass/DarkMode.scss
- resources/sass/TextReader/TextReaderGlossary.scss
This fixes the CSS for issue #244 to properly show the glossary item background colors in all the color modes.
Also, I just wanted to note that it is a bit confusing to have the "New" words display with a "2". It would probably make sense to replace it with an icon or just the word "New", but that should probably be addressed in another issue.
> Fix glossary item colors in light mode

- docker/PythonDockerfile
- tools/tokenizer.py
This allows to install Turkish again from the extra languages tab, but breaks every other language as a result.
One commit also includes a fix for the breaking change in one of the dependencies.
I'm targeting `main` because `hotfix` has not been fast forwarded and I want to keep the diff readable.
> Temporary fix for Turkish

- app/Services/DictionaryImportService.php
Generate `created_at` and `updated_at` timestamps for all supported import dictionaries in the dictionary import service.
Fixes issue #322
I tested each dictionary (only 1 test dictionary each for the wiktionary and dictcc) and the timestamps looked good.
> fix: add supported dictionary timestamps

- app/Services/StatisticsService.php
The new statistic block displays the count of unique lemmas known by the user on the home page. This is helpful for users to get a more accurate picture of their knowns words for a language. Especially for languages which use a lot of declensions.
I thought this would be a good addition to the statistics blocks. Let me know if there's anything you'd like me a change.
> Add lemma count statistic block

- database/migrations/2024_06_22_163858_modify_users_table_4.php
Fix for migration scheme for table 'users'.
When user is more than one, the migration ends with error:
```
linguacafe-test                 |    INFO  Running migrations.
linguacafe-test                 |
linguacafe-test                 |   0001_01_01_000001_create_cache_table .......................... 69.60ms DONE
linguacafe-test                 |   0001_01_01_000002_create_jobs_table ........................... 75.93ms DONE
linguacafe-test                 |   2024_06_22_163858_modify_users_table_4 ........................ 29.23ms FAIL
linguacafe-test                 |
linguacafe-test                 | In Connection.php line 808:
linguacafe-test                 |
linguacafe-test                 |   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' fo …
```
> Fix migration for modify users table
